"""Public API for the match-3 generative simulator."""

import os as _os

# Set before any submodule pulls in pygame, whichever import lands first.
_os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
_os.environ.setdefault("PYGAME_HIDE_SUPPORT_PROMPT", "1")

from .board import (
    apply_swap,
    deal,
    has_match,
    immediate_effect,
    legal_moves,
    match_mask,
    resolve_move,
    settle,
)
from .evidence import (
    EVIDENCE_NAMES,
    EVIDENCE_Q_MATRIX,
    EVIDENCE_SPECS,
    evidence_expectations,
    evidence_metadata,
)
from .policy import (
    ActionDiagnostics,
    move_scores,
)
from .retention import (
    CHURN_SCHEDULE,
    ChurnConfig,
    ChurnSchedule,
    completion_margin,
    expected_mastery_churn,
    MasteryConfig,
    WinPropensityModel,
    mastery_mismatch_hazard,
    sample_C,
    update_mastery,
)
from .scm import (
    DDA_GAINS,
    LEVELS,
    PROXY_NAMES,
    TIER_LOGITS,
    TIER_MOVE_BUDGETS,
    TIER_NAMES,
    Episode,
    ground_truth_model,
    sample_A,
    sample_D,
    sample_E,
    sample_K,
    sample_L,
    sample_R,
    sample_S0,
    sample_S_next,
    sample_X,
)
from .spec import (
    BENCHMARK_CONFIG,
    HORIZONTAL_STRIPE,
    NO_SPECIAL,
    SKILL_COVARIANCE,
    SKILL_NAMES,
    SKILL_PROFILES,
    Action,
    BenchmarkConfig,
    CascadeStep,
    Difficulty,
    LevelContext,
    PlayerSkill,
    State,
    Transition,
    VERTICAL_STRIPE,
)

__version__ = "0.1.0"

__all__ = [
    "Action",
    "ActionDiagnostics",
    "BENCHMARK_CONFIG",
    "BenchmarkConfig",
    "CascadeStep",
    "CHURN_SCHEDULE",
    "ChurnConfig",
    "ChurnSchedule",
    "completion_margin",
        "expected_mastery_churn",
    "DDA_GAINS",
    "Difficulty",
    "Episode",
    "EVIDENCE_NAMES",
    "EVIDENCE_Q_MATRIX",
    "EVIDENCE_SPECS",
    "LEVELS",
    "LevelContext",
    "HORIZONTAL_STRIPE",
    "MasteryConfig",
    "NO_SPECIAL",
    "PROXY_NAMES",
    "PlayerSkill",
    "SKILL_COVARIANCE",
    "SKILL_NAMES",
    "SKILL_PROFILES",
    "State",
    "TIER_LOGITS",
    "TIER_MOVE_BUDGETS",
    "TIER_NAMES",
    "Transition",
    "VERTICAL_STRIPE",
    "WinPropensityModel",
    "apply_swap",
    "deal",
    "evidence_expectations",
    "evidence_metadata",
    "ground_truth_model",
    "has_match",
    "immediate_effect",
    "legal_moves",
    "match_mask",
    "mastery_mismatch_hazard",
    "move_scores",
    "resolve_move",
    "sample_A",
    "sample_C",
    "sample_D",
    "sample_E",
    "sample_K",
    "sample_L",
    "sample_R",
    "sample_S0",
    "sample_S_next",
    "sample_X",
    "settle",
    "update_mastery",
]
